Реализован одновременный запуск FastAPI и бота
Studio-Yandex-Practicum/providenie pull request #177
Opened 2024-11-18 15:35 UTC by Mazarini8

Добавлен файл Dockerfile.fastapi для настройки окружения FastAPI.
Изменён файл docker-compose.dev.yaml для добавления в запуск FastAPI вместе с ботом.
Создан основной файл src/app/main.py для запуска FastAPI и его проверки.
Протестированы оба процесса на локальной машине, оба запускаются корректно.

2024-11-18 19:59 UTC, teamofroman requested changes
Есть ряд замечаний. Надо поправить.

2024-11-18 19:59 UTC, teamofroman commented on docker-compose.dev.yaml
> -        required: true
Без файла окружения не сможет создаться база данных. Поэтому оставляем требование обязательности.

2024-11-18 19:59 UTC, teamofroman commented on Dockerfile.fastapi
> +COPY src/ .
Если делаем запуск бота и fastapi в разных контейнерах, то копировать весь код в контейнер не требуется. Так же как и не надо тащить в контейнер с fastapi зависимости чисто для бота.
Но запуск в разных контейнерах влечет за собой ряд сложностей/вопросов, а именно:
- необходимость поддерживать модель данных и crud и в боте и у fastapi
- следить, что бы миграции делал кто-то один.
- если бот не общается с БД на прямую, то нужно реализовывать API, через который бот будет общаться с fastapi. А это тянет за собой необходимость идентификации бота (что бы кто попало не работал с нашим API)

Поэтому предлагаю сделать совместный запуск бота и fastapi. Как это реализовывается очень хорошо показано в примере https://docs.python-telegram-bot.org/en/v20.0b0/examples.customwebhookbot.html.
Из него надо не все, а только то, что касается совместного запуска.

Попробуй сначала сделать отдельный проект на основе кода примера, что бы понять как это все работает, а потом переноси в основной проект.

Ну и в качестве разминки можно реализовать общение бота и телеграмма через webhook (но это если останется время)

2024-11-20 10:12 UTC, KonstantinRaikhert commented on src/main.py
> +    bot_process = multiprocessing.Process(target=run_bot)
Кажется, что все же для нашего приложение это будет излишне. У нас все же не задачи для сложных вычислений. В забавной [статье](https://habr.com/ru/companies/otus/articles/501056/) неплохо автор разложил.

Итак, предложение - пойти методами, которые предлагают разработчики PTB. В основном хороший вариант с вебхуками. Но и с polling сейчас тоже можно справиться.
В [официальной документации](https://docs.python-telegram-bot.org/en/v20.2/examples.customwebhookbot.html) есть об этом. 
Так же на [StackOverflow](https://stackoverflow.com/questions/76142431/how-to-run-another-application-within-the-same-running-event-loop) тоже есть хороший исчерпывающий ответ от [Chris](https://stackoverflow.com/users/17865804/chris).
А [тут](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#running-ptb-alongside-other-asyncio-frameworks) написано почему именно так стоит реализовывать.

2024-11-20 10:13 UTC, KonstantinRaikhert commented on src/main.py
И да, почему у нас 2 main.py?

2024-11-22 17:26 UTC, teamofroman approved these changes
Принято

2024-11-22 17:26 UTC, merged