Feature/db connect
Studio-Yandex-Practicum/providenie pull request #179
Opened 2024-11-20 03:01 UTC by pullveryzator

Написал crud для взаимодействия с базой. По сути сделал их общими для всех моделей. Любая критика и предложения приветствуются. Наверняка что-то упустил...

2024-11-20 09:22 UTC, teamofroman requested changes
Отлично.
Есть несколько моментов, которые надо поправить.

2024-11-20 09:22 UTC, teamofroman commented on src/app/crud/user_tg.py
> +class CRUDUserTG(CRUDBase):
Для пользователя надо переопределить метод `create` и `update`, т.к. в схеме будет поле `password` с паролем, а в БД мы храним его hash. Т.о. надо будет с словаре, который получится из схемы заменить `password` на `hashed_password` и вписать туда значение хешированного пароля.

2024-11-20 09:22 UTC, teamofroman commented on src/app/crud/base.py
> +        for field in obj_data:
Давай пойдем ноборот. Идем по `update_data`, проверяем, есть ли у `db_obj` аттрибут `field` (`hasattr`) и если есть, устанавливаем его значение.

2024-11-20 09:22 UTC, teamofroman commented on src/app/crud/base.py
> +        update_data = pydantic_scheme_obj.dict(exclude_unset=True)
Давай еще добавим исключение значений, которые установлены в None.

2024-11-20 09:22 UTC, teamofroman commented on src/bot/core/settings.py
> +    postgres_user = ''
Давай для единообразия кода добавим аннатации.
Значения по умолчанию убираем. Без этих данных мы не подключимся к БД.

2024-11-20 09:22 UTC, teamofroman commented on src/bot/core/settings.py
>      class Config:  # noqa: D106
Давай добавим `extra = 'ignore'`, что бы не валиться на тех настройках, которые есть в env-файле, но нет в классе.

2024-11-20 09:32 UTC, teamofroman commented on src/app/crud/base.py
> +    async def _get_by_attribute(
Давай сделаем так, что бы можно было делать фильтрацию по нескольким атрибутам. Все их соединяем по условию `И`

2024-11-20 14:11 UTC, pullveryzator commented on src/app/crud/base.py
> +        for field in obj_data:
Поправил.

2024-11-20 14:12 UTC, pullveryzator commented on src/app/crud/base.py
> +        update_data = pydantic_scheme_obj.dict(exclude_unset=True)
Поправил.

2024-11-20 14:14 UTC, pullveryzator commented on src/bot/core/settings.py
> +    postgres_user = ''
Поправил. Вопрос: нужно ли убирать значения по-умолчанию у других параметров? (в legacy)

2024-11-20 14:15 UTC, pullveryzator commented on src/bot/core/settings.py
>      class Config:  # noqa: D106
Поправил.

2024-11-20 14:15 UTC, pullveryzator commented on src/app/crud/base.py
> +    async def _get_by_attribute(
Сделал по нескольким параметрам. Условия должны приходить в виде словаря.

2024-11-20 14:17 UTC, pullveryzator commented on src/app/crud/user_tg.py
> +class CRUDUserTG(CRUDBase):
С этим пока думаю..

2024-11-20 17:17 UTC, pullveryzator commented on src/app/crud/user_tg.py
> +class CRUDUserTG(CRUDBase):
Реализовал на встроенной функции hash().

2024-11-20 18:15 UTC, teamofroman requested changes
Есть небольшие правки

2024-11-20 18:15 UTC, teamofroman commented on src/app/endpoints/validators.py
> +    existing_user_query = select(UserTG).where(UserTG.tg_id == tg_id)
Для проверки существования записи лучше воспользоваться функцией `exists`, т.к. сам объект нам не нужен.
https://dnmtechs.com/using-sqlalchemys-existence-query-in-python-3/

2024-11-20 18:15 UTC, teamofroman commented on src/app/crud/user_tg.py
> +        await check_tg_id_unique(pydantic_scheme_user, session)
Проверка существования пользователя не задача функции `create`. Ее задача - создать запись в базе. Убеждаться что пользователя с таким tg_id нет должна вызывающая функция.

Аналогично для `update`

2024-11-20 18:15 UTC, teamofroman commented on src/app/crud/user_tg.py
> +        new_user_dict['hashed_password'] = hash(password)
Здесь надо добавить комментарий TODO с пометкой "заменить на получение хеша после создания функций для авторизации"

`# TODO: ...`

Аналогично для `update`

2024-11-20 18:15 UTC, teamofroman commented on src/app/endpoints/validators.py
> +    if existing_user:
Выбрасывать исключение здесь не надо. Достаточно вернуть `True`, если пользователя с таким tg_id нет, и `False` в противном случае.

И т.к. эта функция относится к пользователям, ее можно смело включить в CRUD для работы с пользователем.

2024-11-21 08:25 UTC, pullveryzator commented on src/app/endpoints/validators.py
> +    existing_user_query = select(UserTG).where(UserTG.tg_id == tg_id)
Поправил.

2024-11-21 08:26 UTC, pullveryzator commented on src/app/crud/user_tg.py
> +        await check_tg_id_unique(pydantic_scheme_user, session)
Поправил.

2024-11-21 08:27 UTC, pullveryzator commented on src/app/crud/user_tg.py
> +        new_user_dict['hashed_password'] = hash(password)
Поправил.

2024-11-21 08:27 UTC, pullveryzator commented on src/app/endpoints/validators.py
> +    if existing_user:
Поправил.

2024-11-22 17:29 UTC, teamofroman approved these changes
Принято

2024-11-22 17:47 UTC, merged