Регистрация пользователя в боте
Studio-Yandex-Practicum/providenie pull request #180
Opened 2024-11-20 10:19 UTC by quuenofenigma

При запуске бота пользователем (или выполнении команды /start) информация о нем  заносится в БД.
Если пользователь с таким tg_id есть в БД, проверяем:
если пользователь заблокирован - вывести соответствующее сообщение с контактами администратора для разблокировки, пока выводится только сообщение о блокировке пользователя, не нашел контакты администратора 
если пользователь не активен - обновить его данные и переводим  в активное состояние

2024-11-20 16:09 UTC, teamofroman requested changes
Отлично, но немного поторопился.
Скоро реализуют модели и CRUD функции.
Надо будет обновить свой код в соответствии с изменениями.

2024-11-20 16:09 UTC, teamofroman commented on src/bot/conversations/main_application.py
> +        if db_user and not db_user.is_active:
Не надо пользоаателю знать лишнего.
Поэтому просто выводим приветственное сообщение.

2024-11-21 10:24 UTC, quuenofenigma commented on src/bot/conversations/main_application.py
> +        if db_user and not db_user.is_active:
Исправил, обновил develop, с учетом всех моделей, которые появились сделал
Но пришлось поменять поле tg_id со String на Integer
Сделал новые миграции, проверил, все работает - пользователь добавляется в бд
Мне надо дождаться реализации CRUD?

2024-11-22 18:09 UTC, teamofroman requested changes
Надо поправить в соответствии с изменениями в ветке `develop`

**Предварительно не забудь обновить у себя ветку `develop`, а потом обновить файлы в своей ветке на основе ветки `develop`**

2024-11-22 18:09 UTC, teamofroman commented on src/app/models/models.py
> +    tg_id = Column(Integer, nullable=False)
Integer имеет размер 32 бита. Цитата из доков TelegramBotAPI:
> This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.

Что в вольном изложении - для хранения идентификатора надо **64 битное** число (double не рассматриваем).

PythonTelegramBot может обрабатывать идентификатор и как число и как строку. Что бы избежать дальнейшего роста разрядности (понятно, что не скоро), для хранения идентификатора будем использовать строку.

Поэтому этот файл оставляем без изменений относительно ветки `develop`.

2024-11-22 18:09 UTC, teamofroman commented on src/app/models/db_utils.py
> +async def save_and_commit(
У нас есть CRUD функции для работы с пользователями. Давай использовать их.
(Если их у тебя нет, обнови код в своей ветке из ветки `develop`)

2024-11-22 18:09 UTC, teamofroman commented on src/app/models/db_utils.py
> +async def get_user_by_tg_id(session: AsyncSession, tg_id: int) -> UserTG:
Аналогично предыдущему комментарию

2024-11-22 18:09 UTC, teamofroman commented on src/bot/conversations/main_application.py
> +        db_user = await get_user_by_tg_id(session, tg_user.id)
Заменить на использование CRUD функция для работы с пользователем.

2024-11-22 18:09 UTC, teamofroman commented on src/app/models/db_utils.py
> +    user = await get_user_by_tg_id(session, tg_user.id)
Использовать CRUD для работы с пользователем

2024-11-22 18:09 UTC, teamofroman commented on src/app/models/db_utils.py
> +    await save_and_commit(session, user)
Аналогично

2024-11-22 18:09 UTC, teamofroman commented on src/alembic/versions/2024_11_21_1032-0e3d1d822d4a_migrations_change_tg_id_string_to_number.py
Удали у себя этот файл, обнови свой код из ветки `develop` (предварительно обновив ее у себя)  и, при необходимости, создай новую миграцию.

2024-11-28 18:33 UTC, teamofroman requested changes
Небольшие моменты, которые надо поправить.

2024-11-28 18:33 UTC, teamofroman commented on src/alembic/env.py
> +from src.app.core.base import Base
Папка `src` не является модулем. Она - корневая папка проекта при запуске. Указывать импорты надо относительно нее.

Т.е. в импортах ее указывать не надо.

2024-11-28 18:33 UTC, teamofroman commented on src/app/core/base.py
> +from src.app.core.db import Base
Аналогично про `src`

2024-11-28 18:33 UTC, teamofroman commented on src/bot/conversations/main_application.py
> +from src.app.core.db import get_async_session
Аналогично про `src`

2024-11-28 18:33 UTC, teamofroman commented on src/bot/conversations/main_application.py
> +    async for session in get_async_session():
Здесь надо воспользоваться UserCRUD, для единообразия кода

2024-11-28 18:33 UTC, teamofroman commented on src/bot/conversations/main_application.py
> +            await send_message(
Это сообщение будет показано только для нового пользователя.
Давай будем приветствовать всех пользователей, которые выполнили команду `/start`.

2024-11-28 18:33 UTC, teamofroman commented on src/main.py
> +from src.bot.core import logger  # noqa
Аналогично про `src`

2024-12-01 08:20 UTC, teamofroman approved these changes
Заблокированный юзер никогда не поймет, что он заблокирован 😀, особенно с приветственным сообщением. Поправил.

Принято.

2024-12-01 08:21 UTC, merged