Правка метода update
Studio-Yandex-Practicum/providenie pull request #184
Opened 2024-11-27 18:15 UTC by pullveryzator

Changes to be committed:
	modified:   app/crud/base.py

2024-11-28 19:10 UTC, teamofroman requested changes
Надо немного поправить

2024-11-28 19:10 UTC, teamofroman commented on src/app/crud/base.py
>          update_data = pydantic_scheme_obj.dict(
dict - deprecated метод, вместо него model_dump

2024-11-29 08:20 UTC, pullveryzator commented on src/app/crud/base.py
>          update_data = pydantic_scheme_obj.dict(
Роман, метод model_dump используется в pydantic 2 и выше, а у нас 1.х Или я ошибаюсь?

2024-12-01 08:45 UTC, teamofroman requested changes
Надо немного поправить.

2024-12-01 08:45 UTC, teamofroman commented on src/app/crud/user_tg.py
> +        return {'user': new_user, 'group_names': group_names}
Здесь мы создаем пользователя и возвращаем только его. Остальное - вспомогательная информация. Ее возвращать не надо.

2024-12-01 08:45 UTC, teamofroman commented on src/app/crud/user_tg.py
> +        new_user_dict['hashed_password'] = str(hash(password))  # TODO:
В файле `/src/app/core/jwt.py` есть функции для работы с паролями. Используй их. (Обнови у себя ветку `develop` и подтяни код в свою ветку.

2024-12-01 08:45 UTC, teamofroman commented on src/app/crud/user_tg.py
> +        return {'user': db_user, 'group_names': group_names}
Возвращаем только пользователя.

2024-12-01 08:45 UTC, teamofroman commented on src/app/crud/user_tg.py
> +            update_data['hashed_password'] = str(hash(password))  # TODO:
В файле /src/app/core/jwt.py есть функции для работы с паролями. Используй их. (Обнови у себя ветку develop и подтяни код в свою ветку.

2024-12-03 17:03 UTC, teamofroman requested changes
Совсем чуть-чуть надо поправить

2024-12-03 17:03 UTC, teamofroman commented on src/app/crud/user_tg.py
> +                user_id=new_user.id, group_id=group.id)
`new_user.id` к этому моменту еще не существует. Ты только добавил объект в очередь на создание (session.add(new_user)). Реально в БД его еще нет. Он там появится после коммита. И надо не забыть обновить объект `new_user` из БД (как раз пропишется id созданного пользователя)

2024-12-03 19:08 UTC, pullveryzator commented on src/app/crud/user_tg.py
> +                user_id=new_user.id, group_id=group.id)
Поправил.

2024-12-04 10:20 UTC, teamofroman approved these changes
Принято

2024-12-04 10:30 UTC, merged