Feature/send message
Studio-Yandex-Practicum/providenie pull request #185
Opened 2024-11-28 11:19 UTC by Kate1109

Реализована функция  отправки сообщений пользователям с привязкой к БД и связкой с html формой.

2024-11-28 15:49 UTC, KonstantinRaikhert reviewed
Возможно я упустил какие-то договоренности. И это драфтовый ПР?

2024-11-28 15:49 UTC, KonstantinRaikhert commented on .gitignore
> +src/bot/static/css/bootstrap.rtl.min.css.map
Не совсем понятно, почему в игноре именно эти 4 файла?
Смотрю добавлено много css. Точно ли необходимо нам это всё?
Через CDN не предлагаю, но есть такое подозрение, что далеко не вся эта статика нам необходима)

2024-11-28 15:49 UTC, KonstantinRaikhert commented on src/bot/core/settings.py
> +load_dotenv()
А разве нам нужно тут загружать переменные окружения? Если мы вызываем уже там где к ним обращаемся

2024-11-28 15:49 UTC, KonstantinRaikhert commented on src/bot/app.py
с app.py не понял. У нас точка входа же в другом файле. А тут мы заново пишем и иницируем

2024-11-28 15:49 UTC, KonstantinRaikhert commented on src/bot/app.py
> +async def send_messages(
По хорошему все функции отправки сообщения тогда уже убрать в другое место. Даже создать в структуре отдельную папку, будет удобнее для масштабирования

2024-11-28 15:49 UTC, KonstantinRaikhert commented on src/bot/app.py
> +message_queue = asyncio.Queue()
Кажется, что можно использовать jobqueue, которая есть во [фреймворке](https://docs.python-telegram-bot.org/en/stable/telegram.ext.jobqueue.html)

2024-11-28 19:16 UTC, teamofroman requested changes

2024-11-28 19:16 UTC, teamofroman commented on ruff.toml
> +ignore=["E265", "F811", "D100", "D105", "D104", "D203", "D211", "D213", "N818", "W505", "ANN401", "COM812"]
Этот файл правим по согласованию со мной или Константином.

2024-11-28 19:16 UTC, teamofroman commented on src/app/core/base.py
> +from src.app.core.db import Base  # noqa
`src` не нужно.

2024-11-28 19:16 UTC, teamofroman commented on src/app/crud/user_tg.py
> +from src.app.crud.base import CRUDBase
`src` не нужно

2024-11-28 19:16 UTC, teamofroman commented on src/bot/static/css/bootstrap-grid.css
Зачем на здесь весь bootstrap?
Достаточно bootstrap.css и bootstarp.bundle.js

2024-12-03 16:55 UTC, teamofroman commented
Перешли в другой PR

2024-12-03 16:55 UTC, closed without merging