CI/CD adjustment, fix in main_application.py
Studio-Yandex-Practicum/providenie pull request #189
Opened 2024-12-03 18:02 UTC by Artykays

Для подключения контейнера app к db в .env указал POSTGRES_SERVER=db.
Секреты в репозитории не создавал (нет вкладки Settings), workflow не проверял.
Исправил ошибку в bot.conversations.main_application.py - CRUD-функция ожидала параметр pydantic_scheme_user, а приходил pydantic_scheme_obj.

2024-12-04 09:14 UTC, KonstantinRaikhert commented on docker-compose.yaml
> +    volumes:
можно еще логи постгриса прокинуть на виртуальную машину, а так вроде норм

2024-12-04 09:14 UTC, KonstantinRaikhert commented on docker-compose.yaml
> +      - ./src/.env
по моему сейчас он не найдет env, т.к. в воркфлоу другой путь

2024-12-04 10:33 UTC, teamofroman requested changes
Надо немного поправить

2024-12-05 05:52 UTC, teamofroman approved these changes
Принято

2024-12-05 05:52 UTC, merged